it was broken and made it build failure.
Error: /home/travis/build/1907cloudgcp/Recipease/src/main/java/com/revature/Recipease.java:[16,10] cannot find symbol
cause by the GetMapping symble
bad merge